version: '3'

networks:
  bridge:

volumes:
  mysql_db: {}
  logs: {}

services:
  jibasapp:
    image: php83-jibas:latest # Nama image diubah untuk mencerminkan versi PHP
    build:
      context: ./images/php
    volumes:
      - "./app:/app"
      - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf" # Pastikan file www.conf ini kompatibel atau sesuaikan jika perlu
    networks:
      - bridge
    env_file:
      - .env

  nginx:
    image: nginx:1.21.6 # Anda mungkin perlu mempertimbangkan untuk memperbarui Nginx juga di masa mendatang
    volumes:
      - "./app:/app"
      - "./etc/nginx:/etc/nginx/conf.d"
    networks:
      - bridge
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80

  mysql:
    image: mariadb:11 # Versi MariaDB diperbarui
    volumes:
      - "mysql_db:/var/lib/mysql"
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - bridge
    ports:
      - ${DB_PORT}:3306
