version: '3' # Atribut ini bisa dihapus jika Docker Compose versi terbaru

networks:
  bridge:

volumes:
  mysql_db: {}
  logs: {}

services:
  jibasapp:
    image: php83-jibas:latest
    build:
      context: ./images/php
    volumes:
      - "./app:/app"
      - "./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    networks:
      - bridge
    env_file:
      - .env

  nginx:
    image: nginx:1.21.6
    volumes:
      - "./app:/app"
      - "./etc/nginx:/etc/nginx/conf.d" # Pastikan file konfigurasi Nginx Anda (misal: default.conf) ada di sini
    networks:
      - bridge
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:80"

  mysql: # Layanan MariaDB
    image: mariadb:11
    volumes:
      - "mysql_db:/var/lib/mysql"
      # Tambahkan baris berikut untuk me-mount file konfigurasi kustom MariaDB
      # Pastikan Anda membuat direktori ./etc/mysql/conf.d/
      # dan meletakkan custom-mariadb.cnf di dalamnya.
      - "./etc/mysql/conf.d:/etc/mysql/conf.d"
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - bridge
    ports:
      # Baris ini sudah benar untuk memetakan DB_PORT di host ke port 3306 di kontainer
      - "${DB_PORT}:3306"
